[build]
  publish = "public/"
  command = "pnpm build"

[dev]
  command = "pnpm start"

[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  package = "@netlify/plugin-lighthouse"