backend:
  name: git-gateway
  branch: main

# for local testing
local_backend: true

media_folder: "src/assets/images/blog"
public_folder: "/assets/images/blog"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # path where posts are stored
    create: true # Allow users to create new posts in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # Fields for each post, usually in front-matter
      - { label: "Title", name: "title", widget: "string" }
      - {
              label: "URL Slug",
              name: "url",
              widget: "string",
              hint: 'Specify where the page will be written to. If you use "Blog Post", the post will be accessible from "blog/blog-post"',
        }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - { label: "Image Credit", name: "imageCredit", widget: "string", required: false }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Author", name: "authorName", widget: "string" }
      - { label: "Author Image", name: "authorImage", widget: "image" }
      - { label: "Author Bio", name: "authorBio", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }